#!/usr/bin/env ruby
# frozen_string_literal: true

require 'ambo'

begin
  Ambo.load(Dir.getwd)
rescue Ambo::Error => e
  warn 'An error occurred while running AMBo'
  warn "#{e.class}: #{e.message}"
  warn e.backtrace.join("\n") unless ENV['DEBUG'].nil?
end
